[colors]
[colors.primary]
background = "#010309"
foreground = "#dae6f6"

[colors.normal]
black   = "#010309"
red     = "#fe632d"
green   = "#94bcfb"
yellow  = "#a5ccff"
blue    = "#8fadee"
magenta = "#92b0f1"
cyan    = "#9ac3ff"
white   = "#dae6f6"

[colors.bright]
black   = "#5f6368"
red     = "#e31937"
green   = "#93c6ff"
yellow  = "#a2d7ff"
blue    = "#adcbff"
magenta = "#aecdff"
cyan    = "#99cdff"
white   = "#d1edff"

[colors.cursor]
text   = "#010309"
cursor = "#dae6f6"
