# Background and foreground colors
background = #010309
foreground = #dae6f6

# Standard colors
palette = 0=#010309
palette = 1=#8baaeb
palette = 2=#94bcfb
palette = 3=#a5ccff
palette = 4=#8fadee
palette = 5=#92b0f1
palette = 6=#9ac3ff
palette = 7=#dae6f6

# Bright colors
palette = 8=#5f6368
palette = 9=#abcaff
palette = 10=#93c6ff
palette = 11=#a2d7ff
palette = 12=#adcbff
palette = 13=#aecdff
palette = 14=#99cdff
palette = 15=#d1edff
