background            #010309
foreground            #dae6f6

# black
color0  #010309
color8  #5f6368

# red
color1  #fe632d
color9  #e31937

# green
color2  #94bcfb
color10 #93c6ff

# yellow
color3  #a5ccff
color11 #a2d7ff

# blue
color4  #8fadee
color12 #adcbff

# magenta
color5  #92b0f1
color13 #aecdff

#cyan
color6  #9ac3ff
color14 #99cdff

#white
color7  #dae6f6
color15 #d1edff


